### ISSUE TITLE
Dependency `handy` has unclear status, lacks documentation

### ISSUE THREAD

**Issue by otherjoel** [dstorrs/struct-plus-plus#3]
You took some time to talk to me at BR/RacketCon about struct++, and I’m just starting a branch for replacing some very gnarly code with better stuff using this library! It is going very well so far except for this detail. The docs for the `convert-for` functionality [say][1] “See the handy/hash docs for details” but these docs do not exist (indeed there is a broken link to them in the preceding sentence). I read [elsewhere][2] that you believe that package needs to be broken up, meaning that `handy` is probably not stable. 

The gap in the documentation and the perceived instability make me reluctant to depend on the parts of struct++ that appear mostly to depend on handy.

Ideally, as a dependency of struct++, handy would be in a long-term stable condition with a full set of docs. However, life being what it is, I suspect this will not happen soon? In the absence of that, I have an idle suggestion: it might make more sense to have struct++ “inline” the parts of handy that it uses into private submodules, remove handy as a dependency, and flesh out struct++’s own docs to more fully cover the keyword arguments accepted by the convert-for converters. This would decouple the two packages until handy is more stable, be a quick route to better documentation, and probably cause the least disruption to existing struct++ code.

[1]: https://docs.racket-lang.org/struct-plus-plus/index.html#%28part._convert-for%29
[2]: https://github.com/dstorrs/racket-dstorrs-libs/issues/2#issuecomment-452374572

**Comment by dstorrs** [comment]
On Wed, Aug 21, 2019 at 3:48 PM Joel Dueck <notifications@github.com> wrote:

> You took some time to talk to me at BR/RacketCon about struct++, and I’m
> just starting a branch for replacing some very gnarly code with better
> stuff using this library! It is going very well so far except for this
> detail. The docs for the convert-for functionality say
> <https://docs.racket-lang.org/struct-plus-plus/index.html#%28part._convert-for%29>
> “See the handy/hash docs for details” but these docs do not exist (indeed
> there is a broken link to them in the preceding sentence). I read
> elsewhere
> <https://github.com/dstorrs/racket-dstorrs-libs/issues/2#issuecomment-452374572>
> that you believe that package needs to be broken up, meaning that handy
> is probably not stable.
>

handy is stable and has been for years.  That comment referred to the fact
that it's the first thing I ever wrote in Racket and so it's a kitchen sink
of stuff that could and should be broken out into a set of more specific
libraries.  For example, handy/test-more should be a module unto itself, as
should handy/HTML-Element, handy/web, etc.

As to the docs, it's true that there are not Scribble docs for handy.  It
was written before I knew about Scribble, so there are thorough and
detailed docs, but they are all in the form of comments at the top of each
.rkt file.  I'll pull them out into a README.md as a quick fix and can
Scribblify them when I have tuits.


The gap in the documentation and the perceived instability make me

**Comment by dstorrs** [comment]
Oh, that reminds me:  Here's the docco for hash-remap in case you want it.
Again, I'll scribblify this when I have the tuits.

;; (define/contract (hash-remap h
;;                              #:action-order         [action-order
;;                                                        '(include remove
overwrite
;;                                                          add rename
default)]
;;                              #:include              [include-keys #f]
;;                              #:remove               [remove-keys '()]
;;                              #:overwrite            [overwrite   #f ]
;;                              #:add                  [add         #f ]
;;                              #:rename               [remap       #f ]
;;                              #:default              [default     #f ]
;;                              #:value-is-default?    [default-val #f ]
;;                              #:post                 [post
 identity]
;;                              )
;;   (->* (hash?)
;;        (#:action-order (listof (or/c 'remove 'overwrite 'add 'rename
'default))
;;         #:include list?
;;         #:remove list?
;;         #:overwrite hash?
;;         #:add hash?
;;         #:rename hash?
;;         #:default hash?
;;         #:value-is-default? any/c ; (-> any/c boolean) or converts to
(or/c default-val)
;;         #:post (-> hash? any)
;;        )
;;        hash?)
;;
;;  Mnemonic for default order of application: I ROARenD
;;         include -> remove -> overwrite -> add -> rename -> default
;;
;;    This will munge hashes any way you like.  You can rename keys,
;;    remove keys, overwrite the value of keys, add new keys, ensure
;;    keys exist, and set default values.
;;
;;    The return value is guaranteed to be of the same type (mutable /
;;    immutable) as the original.
;;
;;
;; EXAMPLES:
;;
;;  NOTE: These are listed in the default action order, but you can
;;  change that with the #:action-order parameter.  Whatever order you
;;  specify there will be followed.
;;
;;
;;  INCLUDE the keys specified in the #:include list.  This is really
;;  just syntactic sugar around REMOVE, basically saying "remove
;;  everything except the following keys"
;;
;;    (define h (hash 'group 'fruit   'color 'red    'type 'apple))
;;    (hash-remap h #:include '(group color)   => (hash 'group 'fruit
'color 'red)
;;
;;
;;  REMOVE any values we were told to remove via the #:remove list
;;
;;    (define h (hash 'group 'fruit   'color 'red    'type 'apple))
;;    (hash-remap h #:remove '(group color)   => (hash 'type 'apple)
;;
;;
;;  OVERWRITE values.
;;
;;    (define h (hash 'group 'fruit   'color 'red    'type 'apple))
;;    (hash-remap h #:overwrite (hash 'group 'food))
;;       => (hash 'group 'food 'color 'red 'type 'apple)
;;
;;    If the new value is a procedure of arity 0,1,or 3 then it will be
invoked
;;    and its result will be the new value.  The procedure must have
;;    one of the following signatures:
;;
;;        (-> any/c)                    ; takes no arguments. Returns one
value.
;;        (-> any/c any/c)              ; takes orig-value. Returns one
value.
;;        (-> hash? any/c any/c any/c)  ; takes the hash, key, orig-val.
Returns one value
;;
;;    Procedures of arity other than 0,1,3 will be used directly as the
value.  If you actually
;;    want to use a 0,1,3-arity procedure as the value (e.g. if you're
building a jumptable) then
;;    you'll have to wrap it like so:
;;
;;        (thunk          ; the 'generate a value' procedure
;;          (lambda ...)) ; the procedure it generates
;;
;;    If you ask to overwrite keys that are not there, they will be
;;    added.  If the value to overwrite them with is a 0,1,3-arity
procedure
;;    then the procedure will receive #f as the value for the previously
;;    nonexistent key.
;;
;;
;;  ADD additional keys
;;
;;    NOTE: This will throw an exception if you try to add a key that
;;    is already there. If you want to force a key to a value then use
;;    #:overwrite and it will be added or set as necessary.  If you
;;    want to be sure that a hash has a key then use #:default and it
;;    will only be added if it's not there.  Alternatively, use
;;    #:action-order and put 'remove before 'add.
;;
;;    (define h (hash 'group 'fruit   'color 'red    'type 'apple))
;;    (hash-remap h #:add (hash 'subtype 'honeycrisp))
;;       => (hash 'group 'fruit 'color 'red 'type 'apple 'subtype
'honeycrisp))
;;
;;    (hash-remap h #:add (hash 'group 'tasty)) => EXCEPTION
;;
;;
;;  RENAME keys
;;
;;    (define h (hash 'group 'fruit   'color 'red    'type 'apple))
;;    (hash-remap h #:rename (hash 'color 'shade  'type 'species )
;;       => (hash 'group 'fruit    'shade 'red    'species 'apple)
;;
;;
;;  DEFAULT values if they aren't there or if they have a value that
;;  matches value-is-default? predicate.
;;
;;  The values provided for the defaults can be either:
;;
;;    - A normal value then it will be used directly.
;;    - A procedure of arity 2 then it will be called as (default key hash)
;;    - A procedure of any other arity then it will be called
;;        as (default-val key).
;;
;; The hash that's passed to the arity-2 functions will be a hash of the
same type as the
;; original hash but not eq? to the original hash.  Some or all of the
values will already
;; have been defaulted.  Order of iteration on a hash is unpredictable, so
be careful
;; about using default values that are dependent on other keys that will in
turn be
;; defaulted.
;;
;; If you want your defaulted value to actually be a procedure, as
;; opposed to a value generated by a procedure, then you'll need to wrap
;; it like so:
;;
;;    #:default (hash 'foo (lambda (key) (lambda ...)))
;;
;;  The predicate for value-is-default? can be:
;;
;;    - A single value, which will be matched literally
;;    - A function matching (-> hash? any/c any/c boolean), which receive
hash, key, value
;;    - A function matching (-> any/c boolean?), which will receive the
value
;;
;;  To maintain backwards compatibility you must specify the
#:value-is-default? if you
;;  want to default existing values as opposed to inserting keys that
aren't there.  At
;;  some point I'll make it default to #f, but the original version of this
wouldn't touch
;;  things that were already there.
;;
;;    (hash-remap (hash 'x #f) #:default (hash 'x 7))
=> (hash 'x #f)
;;    (hash-remap (hash 'x 2)  #:default (hash 'x 7))
=> (hash 'x 2)
;;    (hash-remap (hash 'x 2)  #:default (hash 'x 7) #:value-is-default? 2)
=> (hash 'x 7)
;;    (hash-remap (hash 'x 2)  #:default (hash 'x 7) #:value-is-default?
integer?)
;;        => (hash 'x 7)
;;
;;
;; COMPLETE EXAMPLE
;; (define h (hash 'group 'fruit       'color 'red    'type #f))
;; (hash-remap h  #:remove             '(group)
;;                #:overwrite          (hash 'color 'green
;;                                           'type (lambda (k) "fuji")
;;                                           'grower (lambda (hsh key val)
;;                                                     (match val
;;                                                       [#f (hash-ref hsh
'seller "Tom")]
;;                                                       [(? (negate
string?)) (~a val)]
;;                                                       [_ val])))
;;
;;                #:add                (hash 'vendor #f)
;;                #:rename             (hash 'vendor 'seller)
;;                #:default            (hash 'group "group" 'taste ~a
'seller "Bob")
;;                #:value-is-default?  (or/c #f sql-null?)) ; assumes
(require db)
;;
;;     => (hash 'group  "group"     ; removed via #:remove, then added via
#:default
;;              'color  'green      ; overwritten with specified value
;;              'type   "fuji"      ; overwritten with generated value
;;              'grower "Tom"       ; added via overwrite with generated
value
;;              'seller "Bob"       ; added as 'vendor, then renamed, then
defaulted
;;              'taste  "taste")    ; defaulted with generated value
;;
;;  COMPLETE EXAMPLE WITH SPECIFIED ORDER:
;;   (define h (hash 'group 'fruit   'color 'red    'type 'snack 'taste #f))
;;   (hash-remap h
;;               #:action-order '(default add overwrite rename remove)
;;               #:default   (hash 'group 'food 'thump 'tamp 'taste 'yummy)
;;               #:add       (hash 'foo 'bar 'baz 'jaz)
;;               #:overwrite (hash 'foo 'baz)
;;               #:rename    (hash 'foo 'quux 'color 'hue)
;;               #:remove    '(baz)
;;               #:value-is-default? false?)
;;
;;   =>   (hash 'group 'fruit  ; ignored by #:default since the key was
already there
;;              'thump 'tamp   ; defaulted because the key wasn't there
;;              'quux  'baz    ; added as 'foo, then overwritten, then
renamed to 'quux
;;              'hue   'red    ; renamed from 'color
;;              'type  'snack  ; overwritten
;;              'taste 'yummy) ; defaulted due to the #:value-is-default?
predicate
;;

**Comment by otherjoel** [comment]
Thanks for the clarification! This helps me out. No hurry. Thanks again for this great package.

**Comment by dstorrs** [comment]
You're welcome. I'm glad you like it -- I'm pretty proud of it and it's
thrilling to see people using it.
